apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "..serviceAccountName" . }}
  apiGroup: ""
roleRef:
 kind: Role
 name: {{ include "..fullname" . }}
 apiGroup: ""