apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods",]
  verbs: ["create", "get", "delete"]
- apiGroups: [""]
  resources: ["pods/attach"]
  verbs: ["create", "get"]
